worker_processes auto;
events { worker_connections 1024; }
http {
  limit_req_zone $binary_remote_addr zone=api_per_ip:10m rate=20r/s;
  upstream intake { server intake-triage:3000; }
  upstream dispatch { server dispatch-resource:3000; }
  upstream geo { server geospatial-zone:3000; }
  upstream notifications { server notification-status:3000; }

  server {
    listen 8080;
    add_header Access-Control-Allow-Origin "http://localhost:3000" always;
    add_header Access-Control-Allow-Headers "Authorization,Content-Type,Idempotency-Key" always;
    add_header Access-Control-Allow-Methods "GET,POST,PATCH,OPTIONS" always;

    if ($request_method = OPTIONS) { return 204; }

    location = /health { default_type application/json; return 200 '{"service":"local-api-gateway","status":"ready"}'; }
    location = /_health/intake { proxy_pass http://intake/health/ready; }
    location = /_health/dispatch { proxy_pass http://dispatch/health/ready; }
    location = /_health/geospatial { proxy_pass http://geo/health/ready; }
    location = /_health/notification { proxy_pass http://notifications/health/ready; }

    location = /v1/emergencias { limit_req zone=api_per_ip burst=40 nodelay; proxy_pass http://intake; proxy_set_header Authorization $http_authorization; proxy_set_header Content-Type $content_type; }
    location = /v1/emergencias/mias { limit_req zone=api_per_ip burst=40 nodelay; proxy_pass http://intake; proxy_set_header Authorization $http_authorization; }
    location ~ ^/v1/emergencias/zona/ { limit_req zone=api_per_ip burst=40 nodelay; proxy_pass http://geo; proxy_set_header Authorization $http_authorization; }
    location = /v1/despachos { limit_req zone=api_per_ip burst=40 nodelay; proxy_pass http://dispatch; proxy_set_header Authorization $http_authorization; proxy_set_header Content-Type $content_type; }
    location ~ ^/v1/despachos/ { limit_req zone=api_per_ip burst=40 nodelay; proxy_pass http://dispatch; proxy_set_header Authorization $http_authorization; proxy_set_header Content-Type $content_type; }
    location = /v1/notificaciones { limit_req zone=api_per_ip burst=40 nodelay; proxy_pass http://notifications; proxy_set_header Authorization $http_authorization; }
    location = /v1/webhooks { limit_req zone=api_per_ip burst=40 nodelay; proxy_pass http://notifications; proxy_set_header Authorization $http_authorization; proxy_set_header Content-Type $content_type; }
    location = /internal/outbox/process { proxy_pass http://notifications; proxy_set_header Authorization $http_authorization; proxy_set_header Content-Type $content_type; }
  }
}
