FROM public.ecr.aws/lambda/nodejs:22 AS deps
WORKDIR ${LAMBDA_TASK_ROOT}
COPY package*.json ./
RUN npm install --omit=dev --no-audit --no-fund

FROM public.ecr.aws/lambda/nodejs:22
WORKDIR ${LAMBDA_TASK_ROOT}
COPY --from=deps ${LAMBDA_TASK_ROOT}/node_modules ./node_modules
COPY src ./src
CMD ["src/handler.handler"]
